server:
  port: 8080


spring:
  config:
    import: optional:file:.env/local.env
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  application:
    name: JyRESTAPI
  jasypt:
    encryptor:
      algorithm: PBEWithHMACSHA512AndAES_256
      iv-generator-classname: org.jasypt.iv.RandomIvGenerator


---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env/prod.env