server:
  port: 8080

spring:
  application:
    name: JyRESTAPI
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jy_rest_api?sslmode=disable
    username: admin1
    password: ENC(fxR6hLw2RvnELMK9cSu+DvGzka/MJLT+LkBhzapQcumOb/espLDmjxVgYVk3i/48)
  jasypt:
    encryptor:
      algorithm: PBEWithHMACSHA512AndAES_256
      iv-generator-classname: org.jasypt.iv.RandomIvGenerator